version: '3.8'

services:
  mysql:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: db
    ports:
      - "3306:3306"
    volumes:
      - ./sql.sql:/docker-entrypoint-initdb.d/sql.sql

  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"

  frontend:
    build: ./src
    restart: always
    ports:
      - "80:80"
