###
DELETE http://localhost:4000/logout
Content-Type: application/json

{
  "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiaXZhbkBleGFtcGxlLmNvbSIsImlhdCI6MTcwMTUxOTI2NywiZXhwIjoxNzAxNTE5MzI3fQ.3dXAZlGDdYSvtC7a4a7FOq83VfIZGkJ-67bQM9s8xYg"
}

###
POST http://localhost:4000/token
Content-Type: application/json

{
  "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NCwiZW1haWwiOiJpdmFuQGV4YW1wbGUuY29tIiwicGFzc3dvcmQiOiJzZWNyZXRQYXNzd29yZCIsImlhdCI6MTcwMTYyNDg2MywiZXhwIjoxNzAxNjI0OTIzfQ.S9NGs2X7tvhlAkAmGnj_LWGTO7yOczpGZCt2DWVNxsI"
}

###
POST http://localhost:4000/login
Content-Type: application/json

{
  "email": "Admin@mail.com",
  "password": "Admin123"
}

###
POST http://localhost:4000/login
Content-Type: application/json

{
  "email": "user@mail.com",
  "password": "user"
}

###
GET http://localhost:4000/current-user
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NCwiZW1haWwiOiJpdmFuQGV4YW1wbGUuY29tIiwicGFzc3dvcmQiOiJzZWNyZXRQYXNzd29yZCIsImlhdCI6MTcwMTYyNDg2MywiZXhwIjoxNzAxNjI0OTIzfQ.S9NGs2X7tvhlAkAmGnj_LWGTO7yOczpGZCt2DWVNxsI

###
POST http://localhost:4000/register
Content-Type: application/json

{
  "name": "Admin",
  "firstName": "Admin",
  "lastName": "Admin",
  "email": "Admin@mail.com",
  "password": "Admin123",
  "phoneNumber": "9876543210",
  "city": "Санкт-Петербург",
  "age": 25,
   "passportSeries": "CD",
   "passportNumber": "654321",
  "nameOnCard": "PETR PETROV",
  "creditCardNumber": "9876543210987654",
  "expiration": "09/23",
  "CVV": "456",
  "id_deal": 1,
  "role": 2
}
